from __future__ import annotations

from typing import Any
from pydantic import BaseModel, ConfigDict, Field


class PerformanceOperatingPoint(BaseModel):
    """Single point on the engine operating envelope."""
    model_config = ConfigDict(extra="forbid")

    rpm: float
    throttle: float
    engine_load: float
    torque_nm: float
    power_kw: float
    fuel_flow: float
    fuel_efficiency: float


class PerformanceMapResponse(BaseModel):
    """Prototype simulated engine performance map with operating envelope and observed points."""
    model_config = ConfigDict(extra="forbid")

    uav_id: str
    engine_id: str
    envelope_grid: list[PerformanceOperatingPoint] = Field(
        default_factory=list,
        description="Grid of simulated operating points across RPM and Throttle ranges",
    )
    observed_points: list[PerformanceOperatingPoint] = Field(
        default_factory=list,
        description="Real operating points recorded during the current flight/session",
    )
    current_point: PerformanceOperatingPoint | None = None
    disclaimer: str = (
        "Prototype simulated engine performance map generated by AeroTwin physics/digital twin model; "
        "not a certified aircraft-engine calibration map."
    )
